todo_list/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include ("web.urls", namespace="web")),
]

if settings.DEBUG:
    urlpatterns += (
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

web/urls.py
from django.urls import path
from web import views

app_name = "web"

urlpatterns = [
    path("", views.index, name="index"),
    path("register/", views.register, name="register"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    
    path('delete/<int:id>/', views.delete_item, name='delete_item'),
    path('edit/<int:id>/', views.edit_item, name='edit_item'),
    path('done/<int:id>/', views.item_done, name='item_done'),
]

user/models.py
from django.db import models
from django.contrib.auth.models import User

web/models.py
from django.db import models
from django.contrib.auth.models import User

class Item(models.Model):
    name = models.CharField(max_length=255)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    is_complete = models.BooleanField(default=False)

    class Item:
        db_table = "web_item"
        verbose_name = "item"
        verbose_name_plural = "items"
        ordering = ["-id"]


    def __str__(self):
        return self.name
  


class DoneItems(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)

    class DoneItems:
        db_table = "web_doneitems"
        verbose_name = "doneitems"
        verbose_name_plural = "doneitemss"
        ordering = ["-id"]


    def __str__(self):
        return self.name
  

user/views.py
from django.shortcuts import render

# Create your views here.

web/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse

from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout

from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

from web.models import *



from django.shortcuts import redirect

from django.http import JsonResponse




@login_required(login_url='/login')
def index(request):
    user = request.user
    items = Item.objects.filter(user=user, is_complete=False)
    doneitems = Item.objects.filter(user=user, is_complete=True)

    if request.method == 'POST':
        item_name = request.POST.get('item')

        
        itemn = Item.objects.create(
            name=item_name,
            user=user
        )
        itemn.save()
        
        return HttpResponseRedirect(reverse('web:index'))
    else:
        context = {
            "items": items,
            "doneitems": doneitems,
        }

        return render(request, 'web/index.html', context=context)




def register(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        password = request.POST.get('password')

        user = User.objects.create_user(
            username=username,
            first_name=first_name,
            last_name=last_name,
            password=password,
        )
        user.save()
        return HttpResponseRedirect(reverse('web:login'))
    else:
        return render(request, 'web/register.html')

    


def login(request):
    error_message = None
    
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        
        user = authenticate(request, username=username, password=password)
    
        if user is not None:
            auth_login(request, user)
            return HttpResponseRedirect(reverse('web:index'))
        else:
            
            error_message = 'Invalid name or pass.'
    
    return render(request, 'web/login.html', {'error_message': error_message})

    

def logout(request):
    auth_logout(request)

    return HttpResponseRedirect(reverse('web:login'))




@login_required(login_url='/login')
def delete_item(request, id):
    item = Item.objects.get(id=id)
    item.delete()
    return HttpResponseRedirect(reverse('web:index'))


@login_required(login_url='/login')
def edit_item(request, id):
    user = request.user
    itemnow = Item.objects.get(id=id, user=user)

    if request.method == 'POST':
        item_name = request.POST.get('item')
        itemnow.name = item_name
        itemnow.save()
        return HttpResponseRedirect(reverse('web:index'))
    else:
        context = {
            'itemnow': itemnow
        }

    return render(request, 'web/index.html', context=context)


@login_required(login_url='/login')
def item_done(request, id):
    item = Item.objects.get(id=id, is_complete=False)
    item.is_complete = True
    item.save()
    
    return HttpResponseRedirect(reverse('web:index'))

templates/web/edit_item.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Item</title>
    <link rel="stylesheet" href="{% static 'web/css/style.css' %}">
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="text-[#515151]">
    <section id="edit-item" class="max-w-md mx-auto p-6 bg-white rounded-md shadow-md">
        <h1 class="text-2xl font-bold mb-4">Edit Item</h1>
        <form action="" method="post">
            {% csrf_token %}
            <div class="form-control mb-4">
                <label for="item" class="block text-sm font-medium text-gray-700">Item Name</label>
                <input type="text" name="item" id="item" value="{{ item.name }}" class="mt-1 p-2 block w-full border border-gray-300 rounded-md">
            </div>
            <div class="flex justify-end">
                <input type="submit" value="Save" class="bg-blue-500 text-white px-4 py-2 rounded-md hover:bg-blue-600">
            </div>
        </form>
    </section>
</body>
</html>

templates/web/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TODO</title>
    <link rel="stylesheet" href="{% static 'web/css/style.css' %}">
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
    <link href="https://cdn.jsdelivr.net/npm/boxicons@2.0.9/css/boxicons.min.css" rel="stylesheet">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css" />
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <!-- Other head elements -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
</head>
<body class="text-[#515151] w-[50%] mx-auto">
    <div class="flex justify-between items-center">
        <h1 class="text-center text-4xl pt-1">Todo List</h1>
        <a href="{% url 'web:logout' %}" class="flex">
            <i id="logout" class="fa-solid fa-right-from-bracket rotate-180"></i>
            <p id="lo" class="font-bold"></p>
        </a>
    </div>
    <secttion class="">
        <div class="left">
            <form action="" method="post" class="flex justify-between mb-[50px] mt-[50px]">
                {% csrf_token %}
                <input value="{{ itemnow.name }}" type="text" name="item" id="item" placeholder="Enter Task" class="border-[2px] rounded-md outline-none w-full p-2">
                <button type="submit"  class="border-[2px] rounded-md bg-gray-600 text-white p-1 w-[20%]">Add Now</button>
            </form>
        </div>
        <div class="right">
            <h5></h5>
            {% if items %}
            {% for item in items %}
            <ul class="bg-yellow-300 p-2 rounded-md grid grid-cols-7 items-center mb-2">
                <li class="col-span-4">{{ item.name }}</li>
                <a href="{% url 'web:delete_item' item.id %}">
                <li class="col-span-1 bg-red-500 text-white font-semibold py-1 px-2 rounded-md flex items-center hover:bg-red-600 mr-2">
                    <i class="fa fa-trash text-white cursor-pointer mr-2"></i> Delete
                </li>
                </a>
                <a href="{% url 'web:edit_item' item.id %}">
                <li class="col-span-1 bg-blue-500 text-white font-semibold py-1 px-2 rounded-md flex items-center hover:bg-blue-600 mr-2">
                    <i class="fa fa-edit text-white cursor-pointer mr-2"></i>Edit
                </li>
                </a>
                <a href="{% url 'web:item_done' item.id %}">
                <li class="col-span-1 bg-green-500 text-white font-semibold py-1 px-2 rounded-md flex items-center hover:bg-green-600">
                    <i class="fa fa-check-circle mr-2"></i> Done
                </li>
                </a>
            </ul>
            {% endfor %}
            {% else %}
            <h1>No Items</h1>
            {% endif %}
        </div>
        <div class="right mt-8">
            <h5 class="mb-2">Completed Items</h5>
            {% if doneitems %}
            {% for item in doneitems %}
            <ul class="bg-gray-400 p-2 rounded-md w-full items-center mb-2">
                <li class="col-span-4">{{ item.name }}</li>
            </ul>
            {% endfor %}
            {% else %}
            <h1>No Done Items</h1>
            {% endif %}
        </div>
    </secttion>


    <script src="{% static 'web/js/script.js' %}"></script>
</body>
</html>

templates/web/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'web/css/style.css' %}">
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
    <link href="https://cdn.jsdelivr.net/npm/boxicons@2.0.9/css/boxicons.min.css" rel="stylesheet">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css" />
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <!-- Other head elements -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
</head>
<body class="text-gray-700">

    <section id="login" class="min-h-screen flex items-center justify-center bg-gray-100">
        <div class="container mx-auto p-6 max-w-md bg-white shadow-md rounded-lg">
            <form action="" method="post" class="space-y-6">
                {% csrf_token %}
                <div class="logo flex justify-center mb-6">
                    <img src="{% static '/images.jpeg' %}" alt="logo" class="w-16 rounded-full" />
                </div>
                <h1 class="text-2xl font-semibold text-center text-gray-800">Login Now</h1>
                {% if error_message %}
                    <div class="bg-red-300 text-white p-1 rounded-md mb-4">
                        {{ error_message }}
                    </div>
                {% endif %}
                <div class="form-control">
                    <input type="text" name="username" id="username" placeholder="Enter username" class="w-full px-4 py-2 mt-2 border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-400">
                </div>
                <div class="form-control">
                    <input type="password" name="password" id="password" placeholder="Enter password" class="w-full px-4 py-2 mt-2 border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-400">
                </div>
                <p class="text-center text-gray-600">Don't have an account? <a href="{% url 'web:register' %}" class="text-blue-500 hover:underline">Register</a></p>
                <div class="btn">
                    <button type="submit" value="Login" class="w-full px-4 py-2 text-white bg-blue-500 rounded-md hover:bg-blue-600 cursor-pointer">Login</button>
                </div>
            </form>
        </div>
    </section>

    <script src="{% static 'web/js/script.js' %}"></script>
</body>
</html>

templates/web/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Account</title>
    <link rel="stylesheet" href="{% static 'web/css/style.css' %}">
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
    <link href="https://cdn.jsdelivr.net/npm/boxicons@2.0.9/css/boxicons.min.css" rel="stylesheet">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css" />
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <!-- Other head elements -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
</head>
<body class="text-gray-700">

    <section id="login" class="min-h-screen flex items-center justify-center bg-gray-100">
        <div class="container mx-auto p-6 max-w-md bg-white shadow-md rounded-lg">
            <form action="" method="post" class="space-y-6">
                {% csrf_token %}
                <div class="logo flex justify-center mb-6">
                    <img class="w-16 rounded-full" src="{% static '/images.jpeg' %}" alt="logo" />
                </div>
                <h1 class="text-2xl font-semibold text-center text-gray-800">Create Account</h1>
                <div class="form-control">
                    <input type="text" name="username" id="username" placeholder="Enter username" class="w-full px-4 py-2 mt-2 border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-400">
                </div>
                <div class="form-control">
                    <input type="text" name="first_name" id="first_name" placeholder="Enter first name" class="w-full px-4 py-2 mt-2 border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-400">
                </div>
                <div class="form-control">
                    <input type="text" name="last_name" id="last_name" placeholder="Enter last name" class="w-full px-4 py-2 mt-2 border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-400">
                </div>
                <div class="form-control">
                    <input type="password" name="password" id="password" placeholder="Enter password" class="w-full px-4 py-2 mt-2 border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-400">
                </div>
                <p class="text-center text-gray-600">Already have an account? <a href="{% url 'web:login' %}" class="text-blue-500 hover:underline">Login</a></p>
                <div class="btn">
                    <button type="submit" value="Register" class="w-full px-4 py-2 text-white bg-blue-500 rounded-md hover:bg-blue-600 cursor-pointer">Register</button>
                </div>
            </form>
        </div>
    </section>

    <script src="{% static 'web/js/script.js' %}"></script>
</body>
</html>